[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://votre-api.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 